3461 lims sale
Kalenis/kalenislims pull request #34
Opened 2023-02-10 16:47 UTC by pablopadulles

add quantity field in SaleLoadAnalysisStart

2023-02-10 18:18 UTC, ieparszyk requested changes
@pablopadulles Fijate que entró un cambio en el setup.py, aumentando versión de openpyxl.
En ppio n oebería hacerse hasta no hacer un chequeo completo (fijate que justo tiene un comentario). ¿podrás remover esos cambios ? El resto parece OK a primera vista

2023-02-10 18:19 UTC, ieparszyk requested changes
PD: quedó un archivo de lims_industry en este PR también

2023-02-10 19:18 UTC, pablopadulles commented
Hola, ahi lo arregle, perdon me arme un lio con unos branch, y .....

2023-02-16 14:24 UTC, ieparszyk requested changes
@pablopadulles perdón por la demora, fijate que quedó un file de industry acá que se está eliminando.
Abrazo

2023-02-16 23:49 UTC, pablopadulles commented
listo!! ahi agrege el archivo

2023-02-18 14:24 UTC, merged